blueprints/pages.py
from flask import Blueprint, render_template
import pymysql
# Create a blueprint object
offline_bp = Blueprint('offline', __name__)
def read_credentials_from_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
        switchusername = lines[0].strip()  # Get username from the first line
        switchpassword = lines[1].strip()  # Get password from the second line
        databaseusername = lines[2].strip()
        databasepassword = lines[3].strip()
        databasename = lines[4].strip()
        hostname = lines[5].strip()
    return switchusername, switchpassword,databaseusername,databasepassword,databasename,hostname

# File path containing username and password
credentials_file = 'daily/credentials.txt'

# Read username and password from the file
switchusername, switchpassword,databaseusername,databasepassword, databasename,hostname= read_credentials_from_file(credentials_file)
cursorclass =  'pymysql.cursors.DictCursor'
# Define a route within the blueprint
@offline_bp.route('/offline')
def offline_page():
    # Your logic to render the table here
    # For example, rendering a template named offline.html
    # Replace this with your actual logic
    try:
        # Connect to the MySQL database
        connection = pymysql.connect(host=hostname, user=databaseusername, password=databasepassword, database=databasename)
        cursor = connection.cursor()

        with connection.cursor() as cursor:

            # offline list.
            sql_query = "SELECT * FROM apdatabase WHERE status = 'offline';"
            cursor.execute(sql_query)
            offlineAP = cursor.fetchall()

            # Count the offline APs.
            cursor.execute("SELECT COUNT(*) FROM apdatabase WHERE status = 'offline'")
            countoffline = cursor.fetchone()
            countoffline = next(iter(countoffline or []), 0)
    except pymysql.Error as e:
        # Handle any potential MySQL errors
        print(f"Error: {e}")
        offlineAP = []# Set data as empty list in case of an error
        countoffline = []
    return render_template('offline.html', offlineAP=offlineAP,countoffline=countoffline)

@offline_bp.route('/offlineswitch')
def offline_switch():
    # Your logic to render the table here
    # For example, rendering a template named offline.html
    # Replace this with your actual logic
    try:
        # Connect to the MySQL database
        connection = pymysql.connect(host=hostname, user=databaseusername, password=databasepassword, database=databasename)
        cursor = connection.cursor()

        with connection.cursor() as cursor:

            # offline list.
            sql_query = "SELECT * FROM obmanage WHERE status = 'offline';"
            cursor.execute(sql_query)
            offlineswitch = cursor.fetchall()

            # Count the offline APs.
            cursor.execute("SELECT COUNT(*) FROM obmanage WHERE status = 'offline'")
            countoffline = cursor.fetchone()
            countofflineswitch = next(iter(countoffline or []), 0)
    except pymysql.Error as e:
        # Handle any potential MySQL errors
        print(f"Error: {e}")
        countofflineswitch = []# Set data as empty list in case of an error
        offlineswitch = []
    return render_template('offlineswitch.html', countofflineswitch=countofflineswitch,offlineswitch=offlineswitch)

@offline_bp.route('/online')
def online_page():
    # Your logic to render the table here
    # For example, rendering a template named offline.html
    # Replace this with your actual logic
    try:
        # Connect to the MySQL database
        connection = pymysql.connect(host=hostname, user=databaseusername, password=databasepassword, database=databasename)
        cursor = connection.cursor()

        with connection.cursor() as cursor:

            # offline list.
            sql_query = "SELECT * FROM apdatabase WHERE status = 'online';"
            cursor.execute(sql_query)
            onlineAP = cursor.fetchall()

            # Count the offline APs.
            cursor.execute("SELECT COUNT(*) FROM apdatabase WHERE status = 'online'")
            countonline = cursor.fetchone()
            countonline = next(iter(countonline or []), 0)
    except pymysql.Error as e:
        # Handle any potential MySQL errors
        print(f"Error: {e}")
        offlineAP = []# Set data as empty list in case of an error
        countoffline = []
    return render_template('online.html', onlineAP=onlineAP,countonline=countonline)

templates/exampletemplate_don't_move.html
<!DOCTYPE html>
<html lang="en">
<!--This is a template file. Because I feel tired when I think about making tons of pages for different situations with the same form of table-->
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-5.3.2-dist/css/bootstrap.min.css') }}">
    <!--change this to the function of this page-->
    <title>Title</title>
    <!--Main container for the whole page-->
</head>
<body>
    <div class="container px-4 py-5">
        <h2 class="pb-2 border-bottom">What is this actually?</h2>
        <div class="table-responsive">
           <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>IP</th>
                    <th>SN</th>
                    <th>MAC</th>
                    <th>Program_mac</th>
                    <th>Switch_name</th>
                    <th>Port</th>
                    <th>Elv_address</th>
                    <th>Mask</th>
                    <th>Gate</th>
                    <th>Status</th>
                    <th>Update time</th>

                </tr>
            </thead>
            <tbody>
            <!--be sure to change the variable-->
                {% for row in data %}
                <tr>
                    <td>{{row[0]}}</td>
                    <td>{{row[1]}}</td>
                    <td>{{row[2]}}</td>
                    <td>{{row[3]}}</td>
                    <td>{{row[4]}}</td>
                    <td>{{row[5]}}</td>
                    <td>{{row[6]}}</td>
                    <td>{{row[7]}}</td>
                    <td>{{row[8]}}</td>
                    <td>{{row[9]}}</td>
                    <td>{{row[10]}}</td>
                    <td>{{row[12]}}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>

    </div>

    <script src="{{ url_for('static',filename ='bootstrap-5.3.2-dist/js/bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static',filename ='myowns/js/customized.js')}}"></script>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>

<head>
    <title>Data Display from Database</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-5.3.2-dist/css/bootstrap.min.css') }}">

</head>
<body>

    <div class="container mt-4">
        <div class = "container row h2">
            <p class = "text-center">细节数据（点击查看细节列表）</p>
        <div class = "col-md-3">
            <a href = "{{ url_for('offline.offline_page') }}">离线数:{{ countoffline }}</a>
        </div>
        <div class = "col-md-3">
            <a href = "{{ url_for('offline.online_page') }}">在线数:{{ countonline }}</a>
        </div>
        <div class = "col-md-3">
            <a href = "">未安装数:{{ countuninstalled }}</a>
        </div>
        <div class = "col-md-3">
            <a href = "">暂时不装数:{{ countplanned }}</a>
        </div>
    </div>
    </div>
    <br>
    <br>
    <div class="container mt-4">
        <div class = "container row h2">
            <p class = "text-center">大一点的数据XD</p>
        <div class = "col-md-3">
            <p>总计划安装:{{ countoffline+countonline+countuninstalled+countplanned }}</p>
        </div>
        <div class = "col-md-3">
            <p>剩余放装AP:100</p>
        </div>
        <div class = "col-md-3">
            <P>剩余面板AP:100</P>
        </div>
        <div class = "col-md-3">
            <a href = "">重点掉线:{{ countplanned }}</a>
        </div>
    </div>
    </div>

    <div class="container mt-4">
        <div class = "container row h2">
            <p class = "text-center">网工小知识</p>
        <div class = "col-md-3">
            <a>级联线表:{{ countoffline+countonline+countuninstalled+countplanned }}</a>
        </div>
        <div class = "col-md-3">
            <a>vlan规划表</a>
        </div>
        <div class = "col-md-3">
            <a>机柜图</a>
        </div>
        <div class = "col-md-3">
            <a href = "{{ url_for('offline.offline_switch') }}">交换机情况:{{ countswitchoffline }}</a>
        </div>
    </div>
    </div>

    <!--Search function for AP status check-->
    <div class = "container text-center">

    <h1>Search items</h1>
    <form action="/search" method="post">
        <input type="text" name="search" placeholder="Search...">
        <button type="submit">搜索AP</button>
    </form>

    <h2>Search Results</h2>
    <ul>
        {% for item in items %}
            <li>{{ item }}</li>
        {% endfor %}
    </ul>

    {% if search_query %}
        <p>Your search query: <strong>{{ search_query }}</strong></p>
    {% endif %}
</div>

<!--other introductions to the page. About why this is built.-->
 <div class="container px-4 py-5" id="featured-3">
    <h2 class="pb-2 border-bottom">What is this actually?</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
      <div class="feature col">
        <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#collection"/></svg>
        </div>
        <h3 class="fs-2 text-body-emphasis">拓扑工具</h3>
        <p>网络工程师的知识领域，拓扑图，topology代表的是网络领域的分布图。但是对于一个外行人来说，他不想一辈子做外行人，需要一个符合他的认知方式的知识拓扑。而这个页面其实就是我对网络工程认识结果的一个拓扑图。</p>
        <a href="#" class="icon-link">
          没想好
          <svg class="bi"><use xlink:href="#chevron-right"/></svg>
        </a>
      </div>
      <div class="feature col">
        <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#people-circle"/></svg>
        </div>
        <h3 class="fs-2 text-body-emphasis">管理工具</h3>
        <p>在工作上学习知识，那肯定是不脱产的，所以这个页面同时也是个管理工具，用于完成我在现实中的工作。用程序巡查整个医院的网络，然后发现其中的问题。听说公司也会做一个。那可就跟我没啥关系了。</p>
        <a href="#" class="icon-link">
          没想好
          <svg class="bi"><use xlink:href="#chevron-right"/></svg>
        </a>
      </div>
      <div class="feature col">
        <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"/></svg>
        </div>
        <h3 class="fs-2 text-body-emphasis">一个作品</h3>
        <p>这个页面是我的一个作品。我其实一直想做一个这样的，基于物理设备基础的管理器。我不再是去做那些虚无缥缈的东西。而是明确的，物质的，东西。而且还有个问题，网络角度，一家医院的运行到底都需要什么？</p>
        <a href="#" class="icon-link">
          没想好
          <svg class="bi"><use xlink:href="#chevron-right"/></svg>
        </a>
      </div>
    </div>
  </div>
    <form action="/update_database" method="post">
        <button type="submit" id="updateButton" class="btn btn-primary">Update APdatabase</button>
        <div id="status"></div>
    </form>
        <form action="/update_switch" method="post">
        <button type="submit" id="updateSwitch" class="btn btn-primary">Update switch</button>
        <div id="status2"></div>
    </form>
    <script src="static/bootstrap-5.3.2-dist/js/bootstrap.min.js"></script>
    <script src="static/myowns/js/customized.js"></script>
</body>
</html>

templates/offline.html
<!DOCTYPE html>
<html>

<head>
    <title>Offline</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-5.3.2-dist/css/bootstrap.min.css') }}">

</head>
<body>
    <h1>Offline Aps count: {{ countoffline }}</h1>
        <div class="table-responsive">
           <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>name</th>
                    <th>IP</th>
                    <th>SN</th>
                    <th>MAC</th>
                    <th>program_mac</th>
                    <th>switch_name</th>
                    <th>port</th>
                    <th>elv_address</th>
                    <th>mask</th>
                    <th>gate</th>
                    <th>status</th>
                    <th>update_time</th>

                </tr>
            </thead>
            <tbody>
                {% for row in offlineAP %}
                <tr>
                    <td>{{row[0]}}</td>
                    <td>{{row[1]}}</td>
                    <td>{{row[2]}}</td>
                    <td>{{row[3]}}</td>
                    <td>{{row[4]}}</td>
                    <td>{{row[5]}}</td>
                    <td>{{row[6]}}</td>
                    <td>{{row[7]}}</td>
                    <td>{{row[8]}}</td>
                    <td>{{row[9]}}</td>
                    <td>{{row[10]}}</td>
                    <td>{{row[12]}}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
    <div class="container mt-4">
<h1 class = ".col-md-6">Offline Aps for public share: {{ countoffline }}</h1>
    <div class="table-responsive">
       <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>name</th>
                <th>MAC</th>
                <th>program_mac</th>
                <th>switch_name</th>
                <th>port</th>

                <th>status</th>
                <th>record</th>
                <th>updatetime</th>

            </tr>
        </thead>
        <tbody>
            {% for row in offlineAP %}
            <tr>
                <td>{{row[0]}}</td>
                <td>{{row[3]}}</td>
                <td>{{row[4]}}</td>
                <td>{{row[5]}}</td>
                <td>{{row[6]}}</td>

                <td>{{row[10]}}</td>
                <td>{{row[11]}}</td>
                <td>{{row[12]}}</td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
</div>

    <script src="{{ url_for('static',filename ='bootstrap-5.3.2-dist/js/bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static',filename ='myowns/js/customized.js')}}"></script>
</body>
</html>

templates/offlineswitch.html
<!DOCTYPE html>
<html>

<head>
    <title>Offlineswitch</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-5.3.2-dist/css/bootstrap.min.css') }}">

</head>
<body>
    <h1>Offline switch count: {{ countofflineswitch }}</h1>
        <div class="table-responsive">
           <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>网管地址</th>
                    <th>掩码</th>
                    <th>Vlan</th>
                    <th>SN</th>
                    <th>登陆方式</th>
                    <th>设备角色</th>
                    <th>楼层</th>
                    <th>机柜U数</th>
                    <th>弱电间</th>
                    <th>厂商</th>
                    <th>备注</th>

                </tr>
            </thead>
            <tbody>
                {% for row in offlineswitch %}
                <tr>
                    <td>{{row[1]}}</td>
                    <td>{{row[2]}}</td>
                    <td>{{row[3]}}</td>
                    <td>{{row[4]}}</td>
                    <td>{{row[7]}}</td>
                    <td>{{row[8]}}</td>
                    <td>{{row[9]}}</td>
                    <td>{{row[10]}}</td>
                    <td>{{row[11]}}</td>
                    <td>{{row[12]}}</td>
                    <td>{{row[13]}}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>

    <script src="{{ url_for('static',filename ='bootstrap-5.3.2-dist/js/bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static',filename ='myowns/js/customized.js')}}"></script>
</body>
</html>

templates/online.html
<!DOCTYPE html>
<html lang="en">
<!--This is a template file. Because I feel tired when I think about making tons of pages for different situations with the same form of table-->
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-5.3.2-dist/css/bootstrap.min.css') }}">
    <!--change this to the function of this page-->
    <title>online</title>
    <!--Main container for the whole page-->
</head>
<body>
    <div class="container px-4 py-5">
        <h2 class="pb-2 border-bottom">What is this actually?</h2>
        <div class="table-responsive">
           <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>IP</th>
                    <th>SN</th>
                    <th>MAC</th>
                    <th>Program_mac</th>
                    <th>Switch_name</th>
                    <th>Port</th>
                    <th>Elv_address</th>
                    <th>Mask</th>
                    <th>Gate</th>
                    <th>Status</th>
                    <th>Update time</th>

                </tr>
            </thead>
            <tbody>
            <!--be sure to change the variable-->
                {% for row in onlineAP %}
                <tr>
                    <td>{{row[0]}}</td>
                    <td>{{row[1]}}</td>
                    <td>{{row[2]}}</td>
                    <td>{{row[3]}}</td>
                    <td>{{row[4]}}</td>
                    <td>{{row[5]}}</td>
                    <td>{{row[6]}}</td>
                    <td>{{row[7]}}</td>
                    <td>{{row[8]}}</td>
                    <td>{{row[9]}}</td>
                    <td>{{row[10]}}</td>
                    <td>{{row[12]}}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>

    </div>

    <script src="{{ url_for('static',filename ='bootstrap-5.3.2-dist/js/bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static',filename ='myowns/js/customized.js')}}"></script>

</body>
</html>

templates/planned.html
<!DOCTYPE html>
<html lang="en">
<!--This is a template file. Because I feel tired when I think about making tons of pages for different situations with the same form of table-->
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-5.3.2-dist/css/bootstrap.min.css') }}">
    <!--change this to the function of this page-->
    <title>Title</title>
    <!--Main container for the whole page-->
</head>
<body>
    <div class="container px-4 py-5">
        <h2 class="pb-2 border-bottom">What is this actually?</h2>
        <div class="table-responsive">
           <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>IP</th>
                    <th>SN</th>
                    <th>MAC</th>
                    <th>Program_mac</th>
                    <th>Switch_name</th>
                    <th>Port</th>
                    <th>Elv_address</th>
                    <th>Mask</th>
                    <th>Gate</th>
                    <th>Status</th>
                    <th>Update time</th>

                </tr>
            </thead>
            <tbody>
            <!--be sure to change the variable-->
                {% for row in data %}
                <tr>
                    <td>{{row[0]}}</td>
                    <td>{{row[1]}}</td>
                    <td>{{row[2]}}</td>
                    <td>{{row[3]}}</td>
                    <td>{{row[4]}}</td>
                    <td>{{row[5]}}</td>
                    <td>{{row[6]}}</td>
                    <td>{{row[7]}}</td>
                    <td>{{row[8]}}</td>
                    <td>{{row[9]}}</td>
                    <td>{{row[10]}}</td>
                    <td>{{row[12]}}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>

    </div>

    <script src="{{ url_for('static',filename ='bootstrap-5.3.2-dist/js/bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static',filename ='myowns/js/customized.js')}}"></script>

</body>
</html>

templates/uninstalled.html
<!DOCTYPE html>
<html lang="en">
<!--This is a template file. Because I feel tired when I think about making tons of pages for different situations with the same form of table-->
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-5.3.2-dist/css/bootstrap.min.css') }}">
    <!--change this to the function of this page-->
    <title>Title</title>
    <!--Main container for the whole page-->
</head>
<body>
    <div class="container px-4 py-5">
        <h2 class="pb-2 border-bottom">What is this actually?</h2>
        <div class="table-responsive">
           <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>IP</th>
                    <th>SN</th>
                    <th>MAC</th>
                    <th>Program_mac</th>
                    <th>Switch_name</th>
                    <th>Port</th>
                    <th>Elv_address</th>
                    <th>Mask</th>
                    <th>Gate</th>
                    <th>Status</th>
                    <th>Update time</th>

                </tr>
            </thead>
            <tbody>
            <!--be sure to change the variable-->
                {% for row in data %}
                <tr>
                    <td>{{row[0]}}</td>
                    <td>{{row[1]}}</td>
                    <td>{{row[2]}}</td>
                    <td>{{row[3]}}</td>
                    <td>{{row[4]}}</td>
                    <td>{{row[5]}}</td>
                    <td>{{row[6]}}</td>
                    <td>{{row[7]}}</td>
                    <td>{{row[8]}}</td>
                    <td>{{row[9]}}</td>
                    <td>{{row[10]}}</td>
                    <td>{{row[12]}}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>

    </div>

    <script src="{{ url_for('static',filename ='bootstrap-5.3.2-dist/js/bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static',filename ='myowns/js/customized.js')}}"></script>

</body>
</html>